from __future__ import annotations

from pathlib import Path

from app.config.settings import get_content_lab_runtime_relative_dir

BACKEND_DIR = Path(__file__).resolve().parent.parent.parent
ROOT_DIR = BACKEND_DIR.parent.parent

MODELS_DIR = BACKEND_DIR / "models"
UPLOADS_DIR = BACKEND_DIR / "uploads"
OUTPUTS_DIR = BACKEND_DIR / "outputs"
REPORTS_DIR = BACKEND_DIR / "reports"
RUNTIME_DIR = BACKEND_DIR / "runtime"
PROJECTS_RUNTIME_DIR = RUNTIME_DIR / "projects"
CONTENT_LAB_RUNTIME_DIR = BACKEND_DIR / get_content_lab_runtime_relative_dir()
CONTENT_LAB_TTS_RUNTIME_DIR = CONTENT_LAB_RUNTIME_DIR / "tts" / "tasks"
CONTENT_LAB_VOICES_RUNTIME_DIR = CONTENT_LAB_RUNTIME_DIR / "voices"
CONTENT_LAB_MATERIAL_CACHE_DIR = CONTENT_LAB_RUNTIME_DIR / "material_cache"
BROWSER_PROFILES_DIR = RUNTIME_DIR / "browser_profiles"
STUDIO_RUNTIME_DIR = RUNTIME_DIR / "studio_alpha"
STUDIO_TRANSCRIPTION_RUNTIME_DIR = STUDIO_RUNTIME_DIR / "transcriptions" / "tasks"
STUDIO_TTS_TRAINING_RUNTIME_DIR = STUDIO_RUNTIME_DIR / "tts" / "trainings"
STUDIO_DIGITAL_HUMAN_RUNTIME_DIR = STUDIO_RUNTIME_DIR / "digital_human"
STUDIO_DIGITAL_HUMAN_TEMPLATES_DIR = STUDIO_DIGITAL_HUMAN_RUNTIME_DIR / "templates"
STUDIO_DIGITAL_HUMAN_TASKS_DIR = STUDIO_DIGITAL_HUMAN_RUNTIME_DIR / "tasks"
STUDIO_DIGITAL_HUMAN_SYNC_DIR = STUDIO_DIGITAL_HUMAN_RUNTIME_DIR / "sync"
CHANJING_POC_RUNTIME_DIR = RUNTIME_DIR / "digital_human_poc" / "chanjing"
INLOOK_STUDIO_DB_PATH = RUNTIME_DIR / "inlook_studio.db"
STUDIO_ALPHA_DB_PATH = STUDIO_RUNTIME_DIR / "inlook_studio.sqlite3"


def ensure_runtime_directories() -> None:
    for directory in (
        MODELS_DIR,
        UPLOADS_DIR,
        OUTPUTS_DIR,
        REPORTS_DIR,
        RUNTIME_DIR,
        PROJECTS_RUNTIME_DIR,
        CONTENT_LAB_RUNTIME_DIR,
        CONTENT_LAB_TTS_RUNTIME_DIR,
        CONTENT_LAB_VOICES_RUNTIME_DIR,
        CONTENT_LAB_MATERIAL_CACHE_DIR,
        BROWSER_PROFILES_DIR,
        BROWSER_PROFILES_DIR / "douyin",
        BROWSER_PROFILES_DIR / "bilibili",
        STUDIO_RUNTIME_DIR,
        STUDIO_TRANSCRIPTION_RUNTIME_DIR,
        STUDIO_TTS_TRAINING_RUNTIME_DIR,
        STUDIO_DIGITAL_HUMAN_RUNTIME_DIR,
        STUDIO_DIGITAL_HUMAN_TEMPLATES_DIR,
        STUDIO_DIGITAL_HUMAN_TASKS_DIR,
        STUDIO_DIGITAL_HUMAN_SYNC_DIR,
        CHANJING_POC_RUNTIME_DIR,
    ):
        directory.mkdir(parents=True, exist_ok=True)
